version: '3.8'

services:
  OrderManagementApi:
    image: ${DOCKER_REGISTRY-}OrderManagementApi
    container_name: OrderManagementApi
    build:
      context: .
      dockerfile: OrderManagementApi/Dockerfile
    cpus: 1
    mem_limit: "0.5G"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 5000:8080
      - 5001:8081


  OrderManagementApi2:
    image: ${DOCKER_REGISTRY-}loadbalancingapi2
    container_name: OrderManagementApi2
    build:
      context: .
      dockerfile: OrderManagementApi/Dockerfile
    cpus: 1
    mem_limit: "0.5G"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 6000:8080
      - 6001:8081


  OrderManagementApi3:
    image: ${DOCKER_REGISTRY-}loadbalancingapi3
    container_name: OrderManagementApi3
    build:
      context: .
      dockerfile: OrderManagementApi/Dockerfile
    cpus: 1
    mem_limit: "0.5G"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 7000:8080
      - 7001:8081


  OrderManagementApi4:
    image: ${DOCKER_REGISTRY-}loadbalancingapi4
    container_name: OrderManagementApi4
    build:
      context: .
      dockerfile: OrderManagementApi/Dockerfile
    cpus: 1
    mem_limit: "0.5G"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 8000:8080
      - 8001:8081
 

  OrderManagementApi5:
    image: ${DOCKER_REGISTRY-}loadbalancingapi5
    container_name: OrderManagementApi5
    build:
      context: .
      dockerfile: OrderManagementApi/Dockerfile
    cpus: 1
    mem_limit: "0.5G"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 9000:8080
      - 9001:8081


  YARPLoadBalancer.:
    image: ${DOCKER_REGISTRY-}YARPLoadBalancer
    container_name: YARPLoadBalancer
    build:
      context: .
      dockerfile: YARPLoadBalancer/Dockerfile
    cpus: 1
    mem_limit: "0.5G"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 3000:8080
      - 3001:8081
 